apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc
spec:
  type: NodePort
  selector:
    app: coordinates-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    docker build -t yehudagav/coordinates_api:v1 .
docker push yehudagav/coordinates_api:v1